# Generated by Claude 3.7 Sonnet.

# Compiler settings
CXX = clang++
CXXFLAGS = \
	-std=c++23 \
	-I include \
	-O3 \
	-fsanitize=address -fno-omit-frame-pointer \
	-Wall \
	-Wextra \
	-pedantic \
	-Werror

# Default rule to build solution from any .cpp file
# Usage: make FILE=path/to/solution.cpp
$(TARGET): $(FILE) $(wildcard include/**/*.h)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $<

# Clean target to remove built executables
clean:
	rm -rf bin

.PHONY: clean
